[pytest]
filterwarnings =
    ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning
    ignore:datetime\.datetime\.utcnow\(\) is deprecated and scheduled for removal.*:DeprecationWarning
