LocalSocket /run/clamav/clamd.sock
FixStaleSocket true
LocalSocketMode 666
User clamav
Foreground true
LogTime true
LogFile /var/log/clamav/clamd.log
PidFile /run/clamav/clamd.pid
DatabaseDirectory /var/lib/clamav
