export const NOTIFICATION_UNREAD_POLLING_INTERVAL_MS = 45_000;

export const NOTIFICATION_PUSH_AUTOCLOSE_MS = 10_000;
export const NOTIFICATION_PUSH_ERROR_AUTOCLOSE_MS = 14_000;

export const NOTIFICATION_PUSH_MAX_SNACK = 3;
export const NOTIFICATION_PUSH_BURST_THRESHOLD = 3;
export const NOTIFICATION_PUSH_REFRESH_THROTTLE_MS = 1_500;
